### PR TITLE
Add setting to display current time instead of match duration

### PR DESCRIPTION
**Pull request by bennygui**
Fixes issue #11

### CODE REVIEW

**Comment by matco** [comment]
Thanks a lot for your contribution!

I don't have the time right now to do a full review. I will have some time in one week.

However, don't you think that it shouldn't be the time -or- the timer. Maybe the option should just be "Display the time". I think we can find some room on the top of the match screen to display the time.

Also, there is no API in the Garmin SDK to display a well-formatted time?!

**Comment by bennygui** [comment]
I will have to check if there is space at the top of the screen... although it doesn't seems like there is much space.

For the formatted time API, there doesn't seem to be anything but using [System::ClockTime](https://developer.garmin.com/downloads/connect-iq/monkey-c/doc/Toybox/System/ClockTime.html) would probably be simpler.

**Comment by matco** [comment]
The layout of the match screen is dynamic and it should be easy to increase the top margin if the time is displayed.

**Comment by bennygui** [comment]
Added a new commit, the time can be displayed at the top now.

**Comment by matco** [comment]
Again, thanks a lot! With any luck I will release a new version this week.

**Pull request merged**
